### ISSUE TITLE
Docker images for dotnet on pi

### ISSUE THREAD

**Issue by nrandell** [challe/dotnet-core-raspberry-pi#1]
Hi - not really an issue!

Nice site - I've created some docker images that follow this. The repository is at [https://github.com/sceneskope/dotnet-core-pi](https://github.com/sceneskope/dotnet-core-pi)

I'm finding it really easy to build to a docker image and then run that on the PI. Keeps everything simple!

**Comment by challe** [comment]
Great! I'll link to it in the wiki :+1:
