### ISSUE TITLE
Libuv and 1.2.0 packages

### ISSUE THREAD

**Issue by nicolasr75** [challe/dotnet-core-raspberry-pi#2]
First of all many thanks for compiling all this information. You probably saved me hours!
I followed your clear instructions closely and it worked like a charm except for the last step, i.e. _dotnet run_.

This gave me an exception that the entry point lv_loop_size was not found in libuv. I checked my version of libuv and it was 0.10.0! I ran apt-get again but it always grabbed this version. I then downloaded the newest version from there web site and compiled it manually. After that it worked. Maybe others experience the same issue. I tested on a Raspberry PI 3 with Ubuntu 16.04 and Mate desktop.

Another note about the package versions:
the current dotnet webapi template seems to reference packages of version 1.2.0.* now, so I did not have to change anything. The runtime I installed was 2.0.0-beta-001861-00

**Comment by challe** [comment]
I'm so glad to hear! Thanks for letting me know. I will add your libuv issue to the guide and also update the part where you manually had to update the template.
